<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Configurations>Debug;Release;Windows7</Configurations>
		<PublishTrimmed>true</PublishTrimmed>
		<PublishAot>true</PublishAot>
		<Copyright>Derp 2023</Copyright>
		<PackageProjectUrl>http://github.com/NoUDerp/Tiler</PackageProjectUrl>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Platforms>AnyCPU</Platforms>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Windows7'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="10.0.7" />
		<PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="10.0.7" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
	</ItemGroup>

</Project>
